services:
    progrupa.edifact.parser:
        class: EDI\Parser

    progrupa.edifact.reader:
        class: EDI\Reader
        arguments: ["@progrupa.edifact.parser", "@progrupa.edifact.populator.interchange"]

    progrupa.edifact.encoder:
        class: EDI\Encoder
        arguments: ["@progrupa.edifact.printer.annotations", "@progrupa.edifact.printer.segments", "@progrupa.edifact.mapping_loader"]

    progrupa.edifact.populator.interchange:
        class: EDI\Populate\InterchangePopulator
        arguments: ["@annotation_reader", "@progrupa.edifact.populator.message"]

    progrupa.edifact.populator.message:
        class: EDI\Populate\MessagePopulator
        arguments: ["@annotation_reader", "@progrupa.edifact.populator.segment", "@progrupa.edifact.mapping_loader"]

    progrupa.edifact.populator.segment:
        class: EDI\Populate\SegmentPopulator

    progrupa.edifact.mapping_loader:
        class: EDI\Mapping\MappingLoader
        arguments: [%progrupa.edifact.mapping%]

    progrupa.edifact.printer.annotations:
        class: EDI\Printer\AnnotationPrinter
        arguments: ["@annotation_reader"]

    progrupa.edifact.printer.segments:
        class: EDI\Printer\SegmentPrinter
